version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build:
    #executor: python/default
    docker: # Run the steps with Docker. CircleCI Python images available at: https://hub.docker.com/r/circleci/python/
      - image: circleci/python:3.6.4
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
  test:
    docker:
      - image: circleci/python:3.6.4
    steps:
      - checkout
      - python/install-deps
      - run:
          name: Test
          command: python -m pytest -v --junit-xml=test-reports/junit.xml
      - store_test_results:
          path: test-reports
      - store_artifacts:
          path: test-reports

workflows:
  main:
    jobs:
      - build
      - test:
          requires:
              - build