version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    #executor: python/default
    docker: # run the steps with Docker
    # CircleCI Python images available at: https://hub.docker.com/r/circleci/python/
      - image: circleci/python:3.6.4
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: |
            if << parameters.local >>; then
              pip install --user -r requirements.txt
            else
              pip install -r requirements.txt
            fi
          name: Install Dependencies
      - run:
          #command: ./manage.py test
          command: pytest --junitxml=test-reports/junit.xml --html=test-reports/pytest_report.html --self-contained-html
          name: Test
      - store_test_results:
          path: test-reports
      - store_artifacts:
          path: test-reports

workflows:
  main:
    jobs:
      - build-and-test