version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build:
    #executor: python/default
    docker: # Run the steps with Docker. CircleCI Python images available at: https://hub.docker.com/r/circleci/python/
      - image: circleci/python:3.6.4
    steps:
      - checkout
      - python/load-cache       # Loads cached results from the previous iteration of the build job (saves time).
      - python/install-deps     # Installs app dependencies (e.g. Python packages) listed in requirements.txt
      - python/save-cache       # Saves build results in cache for the next iteration of the build job.
  test:
    docker:
      - image: circleci/python:3.6.4
    steps:
      - checkout                # These repeated steps are needed because the two jobs are independent.
      - python/install-deps     # Can be avoided by passing a workspace from the build job to the test job.
      - run:
          name: Test
          command: python -m pytest -v --junit-xml=test-reports/junit.xml
      - store_test_results:
          path: test-reports
      - store_artifacts:
          path: test-reports

workflows:
  main:
    jobs:
      - build
      - test:
          requires:
              - build